sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_script:
  - docker-compose build
after_success:
  - docker login --username=_ --password="$HER_AUTH_TOK" registry.heroku.com
  - docker build -t registry.heroku.com/blog-api-backend/web -f Dockerfile .
  - docker push registry.heroku.com/blog-api-backend/web
