version: 2
jobs:
  machine:
    services:
      - docker 
  dependencies:
    cache_directories:
      - ~/docker 
  build:
    docker:
      - image: circleci/node:7.10 
    working_directory: ~/basic-blog-api
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deployment:
    staging:
      branch: master
      commands:
        - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        - docker build --rm=false -t registry.heroku.com/blog-api-backend/web -f Dockerfile .
        - docker push registry.heroku.com/blog-api-backend/web